title: Jekyll Documentation
description:
baseurl: /jekyll-documentation
url: https://someimportantcompany.github.io
repository: someimportantcompany/jekyll-documentation

permalink: pretty
include:
  - README.md
exclude:
  - .jekyll-cache/
  - .sass-cache/
  - assets-dev/
  - node_modules/
  - .htaccess
  - LICENSE.md
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js

defaults:
  - scope:
      path: ""
    values:
      layout: default
