title: Jekyll Documentation
description:
baseurl: /jekyll-documentation
url: https://someimportantcompany.github.io
repository: someimportantcompany/jekyll-documentation

header:
  title: Jekyll Documentation
  links:
    - label: View on Github
      url: https://github.com/someimportantcompany/jekyll-documentation

sidebar:
  navigation:
    - label: Home
      url: /
    - label: Configuration
      url: /configuration

footer:
  back-to-top:
    label: Back to top
  content: >-
    Copyright © 2023 <a href="https://someimportantcompany.github.io" target="_blank">Some Important Company</a>.
    <a href="https://github.com/someimportantcompany/jekyll-documentation/blob/master/LICENSE" target="_blank">MIT License</a>.
  gh-edit-link:
    repository: someimportantcompany/jekyll-documentation
    branch: master
    view: tree

permalink: pretty
exclude:
  - .jekyll-cache/
  - .sass-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .htaccess
  - README.md
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
